### ISSUE TITLE
Drag and Drop not working correctly

### ISSUE THREAD

**Issue by caiokawasaki** [phphe/vue-draggable-nested-tree#57] opened 2019-02-05 20:54 UTC
I'm creating an application but my drag and drop is not working properly, especially in the first level. What can it be?

Also `store.deleteNode` is not working...

I put my code here: [https://codesandbox.io/s/03z75682yl](https://codesandbox.io/s/03z75682yl)

Another bug I encountered trying to solve the problem: Sometimes the steps duplicate.

Strange because a while ago everything worked correctly, I spent some time without messing with the project and now that I came back with the project the plugin does not want to work correctly

**Comment by phphe** [comment] 2019-02-11 07:39
Hi. I spent hours to check it. This issue is caused by Vue@2.6 latest.
In your demo: https://codesandbox.io/s/03z75682yl
package.json, change "vue": "^2.5.22" to "vue": "2.5.22", then it works because vue 2.5 is using.

**Comment by phphe** [comment] 2019-02-11 09:30
This is an issue of vue-draggable-nested-tree. It don't work with Vue 2.6, so you get it. Fixed in 2.2.6

**Comment by caiokawasaki** [comment] 2019-02-13 12:59
Everything is alright now

**Closed** 2019-02-17 07:52 UTC
